set1 = {8, 16, 24, 32, 44}
set2 = {7, 14, 8, 32, 21}
differenceset1_set2 = sorted(set1 - set2)
differenceset2_set1 = sorted(set2 - set1)
union_of_set = sorted(set1 | set2)
symmetricdifference_set2_set1 = sorted(set2 ^ set1)
symmetricdifference_set1_set2 = sorted(set1 ^ set2)
set_intersection_set1_set2 = sorted(set1 & set2)
set_intersection_set2_set1 = sorted(set2 & set1)
print("Set Difference:")
print(differenceset1_set2)
print(differenceset2_set1)
print("Union of Sets:")
print(union_of_set)
print("Symmetric Difference:")
print(symmetricdifference_set2_set1)
print(symmetricdifference_set1_set2)
print("Set Intersection:")
print(set_intersection_set2_set1)
print(set_intersection_set1_set2)